# Generated by Django 3.1.6 on 2021-02-24 12:41

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelVilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=1000)),
                ('media_file_type', models.FileField(null=True, upload_to=chat.models.generate_media_path)),
                ('file_type', models.CharField(max_length=6)),
                ('message_unread', models.BooleanField(default=False)),
                ('sent_from_delete', models.BooleanField(default=False)),
                ('sent_by_delete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_id', models.CharField(max_length=20)),
                ('message_state', models.CharField(max_length=7)),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_channel_name', to='chat.channelvilla')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_name', models.CharField(max_length=29)),
                ('chat_room_description', models.CharField(max_length=50)),
                ('message_by_admin', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cover_image', models.ImageField(default='default_image.jpg', upload_to=chat.models.generate_media_path)),
                ('message_id', models.CharField(max_length=20)),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_channel', to='chat.channelvilla')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelBindingIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binded_channel', to='chat.channelvilla')),
                ('connected_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_reveiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
