# Generated by Django 3.1.6 on 2021-02-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatroom',
            old_name='message_id',
            new_name='room_id',
        ),
    ]
