# Generated by Django 3.1.6 on 2021-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210225_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelvilla',
            name='channel_name',
            field=models.CharField(max_length=35),
        ),
    ]
