# Generated by Django 3.1.6 on 2021-02-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210225_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatroom',
            name='room_id',
            field=models.CharField(max_length=35),
        ),
    ]
