# Generated by Django 3.1.6 on 2021-02-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210225_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelbindingidentity',
            name='channel_name_type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
