# Generated by Django 3.1.6 on 2021-02-28 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_channelbindingidentity_channel_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelbindingidentity',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
