# Generated by Django 3.1.6 on 2021-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210228_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markasread',
            name='channel_name',
        ),
        migrations.AddField(
            model_name='markasread',
            name='message_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
