# Generated by Django 3.1.6 on 2021-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210228_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='media_file_type',
            new_name='media_file',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.CharField(max_length=35),
        ),
    ]
