# Generated by Django 3.1.6 on 2021-03-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210301_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_unread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrk_as_read', to='chat.markasread'),
        ),
    ]
