# Generated by Django 3.1.6 on 2021-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20210301_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_state',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
