# Generated by Django 3.1.6 on 2021-03-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210301_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='markasread',
            name='channel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_channel_mark_as_read', to='chat.channelvilla'),
        ),
    ]
