# Generated by Django 3.1.6 on 2021-03-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_markasread_channel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'get_latest_by': 'created_on'},
        ),
    ]
