# Generated by Django 3.1.6 on 2021-03-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210306_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='markasread',
            name='media_type',
            field=models.CharField(default='Text', max_length=5),
        ),
    ]
