# Generated by Django 3.1.6 on 2021-02-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210225_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneBook',
        ),
    ]
