# Generated by Django 3.1.6 on 2021-02-25 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_delete_phonebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('number', models.CharField(max_length=29, unique=True)),
                ('phone_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_stored_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
