# Generated by Django 3.1.6 on 2021-02-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phonebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonebook',
            old_name='name',
            new_name='contact_name',
        ),
    ]
