# Generated by Django 3.1.6 on 2021-02-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210225_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='contact_name',
            field=models.CharField(max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.CharField(max_length=29, null=True, unique=True),
        ),
    ]
