# Generated by Django 3.1.6 on 2021-02-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210225_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
