# Generated by Django 3.1.6 on 2021-02-25 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_contactlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='contact_name',
            field=models.CharField(max_length=29),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=29, unique=True),
            preserve_default=False,
        ),
    ]
