# Generated by Django 3.1.6 on 2021-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210225_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Hey, there! I am using Whatsapp', max_length=200),
        ),
    ]
