# Generated by Django 3.1.6 on 2021-02-25 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20210225_1857'),
        ('accounts', '0012_currentlybindedcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlybindedcontact',
            name='app_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_user_init', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currentlybindedcontact',
            name='channel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_init', to='chat.channelvilla'),
        ),
    ]
