# Generated by Django 3.1.6 on 2021-02-26 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20210226_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlybindedcontact',
            name='app_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
