# Generated by Django 3.1.6 on 2021-02-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20210226_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlybindedcontact',
            name='added_contact_runner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='local_contact', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentlybindedcontact',
            name='app_runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_user_init', to=settings.AUTH_USER_MODEL),
        ),
    ]
