# Generated by Django 3.1.6 on 2021-02-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210225_1857'),
        ('accounts', '0016_auto_20210226_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlybindedcontact',
            name='contact_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locally_saved_channel_name', to='chat.channelvilla'),
        ),
    ]
