# Generated by Django 3.1.6 on 2021-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210226_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.CharField(max_length=29),
        ),
    ]
