# Generated by Django 3.1.6 on 2021-02-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210227_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='number',
            field=models.CharField(max_length=19),
        ),
    ]
