# Generated by Django 3.1.6 on 2021-02-28 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210227_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlybindedcontact',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
